# Generated by Django 4.0.1 on 2022-04-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='Links',
            new_name='Link',
        ),
    ]
